dubbo:
  application:
    name: search-api
  registry:
    protocol: zookeeper
    address: 39.107.252.103:2181
  protocol:
    port: 20881
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/v16?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  data:
    solr:
      host: http://39.107.252.103:8081/solr
#    druid:
#          initial-size: 10
#          max-active: 100
#          min-idle: 10
#          filter:
#            config:
#              enabled: true
#          connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
#publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIJYf+tT6xAojyzf2tiDAYCHDIoN7gyJfz/6Ppnc5x89muxWleII4Bgy738D7wEzB5oh8+WtS9G9Y88IsULkDLUCAwEAAQ==




server:
  port: 8881
image:
  server: http://39.107.252.103/
