dubbo:
  application:
    name: cart-api
    qos-port: 33333
  registry:
    protocol: zookeeper
    address: 39.107.252.103:2181
  protocol:
    port: 20883
spring:
  redis:
    host: 39.107.252.103
    port: 6379
    password: "123"
    jedis:
      pool:
        max-active: 66

server:
  port: 8083
