dubbo:
  application:
    name: background-web
  registry:
    protocol: zookeeper
    address: 39.107.252.103:2181
server:
  port: 9091

spring:
  thymeleaf:
    cache: false
  rabbitmq:
    host: 47.103.21.241
    port: 5672
    username: xxm
    password: 123
    virtual-host: /xxm
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 39.107.252.103:22122

image:
  server: http://39.107.252.103/
